apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-http
  namespace: default
spec:
  rules:
    - host: guestbook-ui.test.com
      http:
        paths:
        - path: /
          backend:
            serviceName: guestbook-ui
            servicePort: 80
